#!/usr/bin/env bash
# Completes DEPLOYMENT_DECKLINK_TEST_SERVER.md steps 6–9 for /opt/titulus.
# Usage: sudo bash /opt/titulus/ops/complete-deploy-steps-6-9.sh
# Optional: TITULUS_SERVER_NAME=example.com sudo -E bash ...
set -euo pipefail

if [[ "${EUID}" -ne 0 ]]; then
  echo "Run as root: sudo bash $0" >&2
  exit 1
fi

REPO=/opt/titulus
NODE_VERSION=20.20.2
SERVER_NAME="${TITULUS_SERVER_NAME:-_}"
ENV_FILE=/etc/titulus/titulus.env
PASS_FILE=/etc/titulus/bootstrap-admin-password.txt

if [[ ! -x "$REPO/engine/build/Release/bg_engine" ]]; then
  echo "Missing engine binary: $REPO/engine/build/Release/bg_engine" >&2
  exit 1
fi
if [[ ! -s "$REPO/backend/public/bg-runtime.js" ]]; then
  echo "Missing bg-runtime.js — finish step 4 first" >&2
  exit 1
fi

install -d -o titulus -g titulus -m 0750 /var/lib/titulus /var/lib/titulus/uploads
install -d -o titulus -g titulus -m 0750 /var/cache/titulus/engines
install -d -o root -g titulus -m 0750 /etc/titulus
install -d -m 0755 /usr/local/lib/titulus
install -d -o titulus -g titulus -m 0755 "$REPO/logs"

# Ensure titulus user has the pinned Node version
sudo -iu titulus bash <<EOF
set -euo pipefail
export NVM_DIR="\$HOME/.nvm"
. "\$NVM_DIR/nvm.sh"
nvm install ${NODE_VERSION}
nvm alias default ${NODE_VERSION}
nvm use ${NODE_VERSION}
node --version | grep -F '${NODE_VERSION}'
npm --version
EOF

# Step 6: env (keep existing password if file already present)
if [[ -f "$ENV_FILE" ]] && grep -q 'TITULUS_ADMIN_PASSWORD=' "$ENV_FILE" \
  && ! grep -q 'REPLACE_WITH_A_NEW_PASSWORD' "$ENV_FILE"; then
  echo "Keeping existing $ENV_FILE"
else
  ADMIN_PASSWORD="$(openssl rand -base64 36)"
  umask 027
  cat >"$ENV_FILE" <<EOF
TITULUS_HOST=127.0.0.1
TITULUS_CONNECT_HOST=127.0.0.1
TITULUS_FE_PORT=3011
TITULUS_BE_PORT=3002
TITULUS_DATA=/var/lib/titulus
CACHE_ROOT=/var/cache/titulus/engines
ENGINE_BIN=/opt/titulus/engine/build/Release/bg_engine

TITULUS_ADMIN_USER=admin
TITULUS_ADMIN_PASSWORD=${ADMIN_PASSWORD}
TITULUS_API_USER=admin
TITULUS_API_PASSWORD=${ADMIN_PASSWORD}

# Phase 20 visual deployment default. Do not set accumulator here.
TITULUS_DEV_PACING_MODE=one_tick
TITULUS_PACING_MODE=one_tick
EOF
  chown root:titulus "$ENV_FILE"
  chmod 0640 "$ENV_FILE"
  printf '%s\n' "$ADMIN_PASSWORD" >"$PASS_FILE"
  chown root:titulus "$PASS_FILE"
  chmod 0640 "$PASS_FILE"
  echo "Wrote $ENV_FILE (bootstrap password also in $PASS_FILE)"
fi

# Step 7: Nginx (LAN-friendly; set TITULUS_SERVER_NAME for a real DNS name)
cat >/etc/nginx/sites-available/titulus-test <<EOF
# Titulus DeckLink test stand — generated by complete-deploy-steps-6-9.sh
server {
    listen 80;
    server_name ${SERVER_NAME};
    client_max_body_size 200M;

    location / {
        proxy_pass http://127.0.0.1:3011;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }

    location /api/ {
        proxy_pass http://127.0.0.1:3002;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }

    location /ws {
        proxy_pass http://127.0.0.1:3002;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_read_timeout 86400s;
    }

    location /uploads/ { proxy_pass http://127.0.0.1:3002; }
    location /fonts/ { proxy_pass http://127.0.0.1:3002; }
    location = /channel.html { proxy_pass http://127.0.0.1:3002; }
    location = /bg-runtime.js { proxy_pass http://127.0.0.1:3002; }
}
EOF

ln -sf /etc/nginx/sites-available/titulus-test /etc/nginx/sites-enabled/titulus-test
rm -f /etc/nginx/sites-enabled/default
nginx -t
systemctl reload nginx

if command -v ufw >/dev/null 2>&1; then
  ufw allow OpenSSH || true
  ufw allow 'Nginx Full' || true
  # Non-interactive enable if inactive
  if ufw status | grep -qi inactive; then
    ufw --force enable || true
  fi
fi

# Step 8: systemd wrapper (pinned Node ${NODE_VERSION})
cat >/usr/local/lib/titulus/start.sh <<EOF
#!/usr/bin/env bash
set -euo pipefail
export NVM_DIR=/home/titulus/.nvm
. "\$NVM_DIR/nvm.sh"
nvm use ${NODE_VERSION} >/dev/null
exec /opt/titulus/dev-start.sh
EOF
chmod 0755 /usr/local/lib/titulus/start.sh

cat >/etc/systemd/system/titulus.service <<'EOF'
[Unit]
Description=Titulus DeckLink test stack
Wants=network-online.target
After=network-online.target

[Service]
Type=oneshot
User=titulus
Group=titulus
WorkingDirectory=/opt/titulus
EnvironmentFile=/etc/titulus/titulus.env
ExecStart=/usr/local/lib/titulus/start.sh
ExecStop=/opt/titulus/dev-stop.sh
RemainAfterExit=yes
TimeoutStartSec=15min
TimeoutStopSec=90s

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable --now titulus.service

# Step 9: acceptance checks
sleep 3
systemctl status titulus --no-pager || true
curl -sf http://127.0.0.1:3002/api/health | jq .
test -s /var/lib/titulus/app.db
test -s /opt/titulus/backend/public/bg-runtime.js
sudo -u titulus test -w /var/lib/titulus/uploads

echo
echo "=== Deploy steps 6–9 complete ==="
echo "Node:        ${NODE_VERSION}"
echo "Repo:        ${REPO}"
echo "Nginx name:  ${SERVER_NAME}"
echo "LAN URL:     http://$(hostname -I | awk '{print $1}')/"
echo "Health:      http://127.0.0.1:3002/api/health"
if [[ -f "$PASS_FILE" ]]; then
  echo "Admin user:  admin"
  echo "Admin pass:  $(cat "$PASS_FILE")"
  echo "(also stored in $PASS_FILE, mode 0640 root:titulus)"
fi
echo
echo "Next: open UI, create DeckLink channels in Settings, then:"
echo "  sudo systemctl restart titulus"
echo "Then run step 10 acceptance (pacing=one_tick / DeckLink logs)."
if [[ "$SERVER_NAME" == "_" ]]; then
  echo
  echo "TLS skipped (no DNS name). To enable later:"
  echo "  TITULUS_SERVER_NAME=your.domain sudo -E bash $0"
  echo "  # or: sudo certbot --nginx -d your.domain"
fi
